Create symbolic link in case /etc/resolv.conf doesn't exist yet
Ocasionally, /etc/resolv.conf doesn't exist yet when the prepender runs.
This creates the link or static file as needed depending on whether
systend-resolved is enabled.

Signed-off-by: John Fortin <fortinj66@gmail.com>

diff --git a/templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml b/templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
--- a/templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
+++ b/templates/common/on-prem/files/NetworkManager-resolv-prepender.yaml
@@ -38,9 +38,14 @@ contents:
     EOF
         # Ensure resolv.conf exists and contains nameservers before we try to run podman
         if [[ ! -e /etc/resolv.conf ]] || ! grep -q nameserver /etc/resolv.conf; then
-            cp /var/run/NetworkManager/resolv.conf /etc/resolv.conf
+            if systemctl -q is-enabled systemd-resolved; then
+                >&2 echo  "NM resolv-prepender: /etc/resolv.conf missing. creating link to /run/systemd/resolve/stub-resolv.conf"
+                cd /etc/ && ln -s ../run/systemd/resolve/stub-resolv.conf /etc/resolv.conf
+            else
+                >&2 echo  "NM resolv-prepender: /etc/resolv.conf missing.  Copying from /var/run/NetworkManager/resolv.conf"
+                cp /var/run/NetworkManager/resolv.conf /etc/resolv.conf
+            fi
         fi
-
 
         NAMESERVER_IP=$(/usr/bin/podman run --rm \
             --authfile /var/lib/kubelet/config.json \
